### PR TITLE
Applies snapshot deploy script to library and app

### LINKED ISSUE #38: Automatic deployment of snapshot builds

### PR DESCRIPTION
**Pull request by ecgreb**
Adds separate gradle.properties with POM info for each

Closes #38

### CODE REVIEW

**Comment by ecgreb** [comment]
Snapshots are now automatically deployed on each successful build of master.

cc @bleege @zugaldia @twbell

**Comment by zugaldia** [comment]
@ecgreb: Fantastic, thank you!

**Comment by mjcunningham** [comment]
:+1: :+1:

**Comment by bleege** [comment]
Awesome!  Just found the latest here -->

https://oss.sonatype.org/content/repositories/snapshots/com/mapzen/android/lost/1.0.2-SNAPSHOT/

**Pull request merged**
