### PR TITLE
Adding Geofencing  [WIP]

### PR DESCRIPTION
**Pull request by friesenkiwi**
Starting to tackle #10 
This is work in progress, I only implemented rough data structures, changed and added interfaces according to google docs, also there is one method deprecated now.

I just wanted to make sure, it looks OK for you and I didn't violate any code style or other guidelines?
Does it look OK to you so far? Is it worth the trouble to continue implementation or are you already on it?

### CODE REVIEW

**Comment by ecgreb** [comment]
This is great thanks for getting the geofencing work started.

I think we'll want to leverage classes in the framework as much as possible since the LocationManager already supports proximity alerts.

[https://developer.android.com/reference/android/location/LocationManager.html#addProximityAlert(double, double, float, long, android.app.PendingIntent)](https://developer.android.com/reference/android/location/LocationManager.html#addProximityAlert(double, double, float, long, android.app.PendingIntent))

As for code style for the most part this looks fine. I'm going to be adding checkstyle to the project shortly. Checks will be based on style defined at https://github.com/mapzen/open/blob/master/checkstyle.xml.

**Comment by friesenkiwi** [comment]
OK, thank you for the encouragement and hints for checkstyle and proximity alerts! :-)
I will work on this to include the suggestions and missing features. Unfortunately, I will need to pause a bit on this for two or three weeks, so if anybody likes to work on it in the meantime, I'll be fine with that.

Is it OK for you if we first implemented a working and sensible subset of methods for a next release, or would you require a complete set as a whole?

**Comment by ecgreb** [comment]
Working subset is fine. That's kind of what this project is all about ;)

**Comment by ecgreb** [comment]
Closing due to inactivity. Feel free to re-open if you start up work again on this issue.

**Pull request closed without merging**
